/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.rapid.adaptor.ctp.serializable.avro.shared;
/** 事件来源 */
@org.apache.avro.specific.AvroGenerated
public enum EventSource implements org.apache.avro.generic.GenericEnumSymbol<EventSource> {
  MD, TD  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"EventSource\",\"namespace\":\"io.rapid.adaptor.ctp.serializable.avro.shared\",\"doc\":\"事件来源\",\"symbols\":[\"MD\",\"TD\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
