/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.horizon.market.serializable.enums;
/** 行情订阅状态 */
@org.apache.avro.specific.AvroGenerated
public enum EnumAvSubscribeStatus implements org.apache.avro.generic.GenericEnumSymbol<EnumAvSubscribeStatus> {
  Succeed, PartSucceed, Failed  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"EnumAvSubscribeStatus\",\"namespace\":\"io.horizon.market.serializable.enums\",\"doc\":\"行情订阅状态\",\"symbols\":[\"Succeed\",\"PartSucceed\",\"Failed\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
