/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.cygnuxltb.jcts.core.ser.enums;
/** 行情类型 */
@org.apache.avro.specific.AvroGenerated
public enum MarketDataType implements org.apache.avro.generic.GenericEnumSymbol<MarketDataType> {
  DEPTH, FAST, LEVEL10, LEVEL20, LEVEL30  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"MarketDataType\",\"namespace\":\"io.cygnuxltb.jcts.core.ser.enums\",\"doc\":\"行情类型\",\"symbols\":[\"DEPTH\",\"FAST\",\"LEVEL10\",\"LEVEL20\",\"LEVEL30\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
