/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.cygnuxltb.jcts.core.ser.enums;
@org.apache.avro.specific.AvroGenerated
public enum OrdValid implements org.apache.avro.generic.GenericEnumSymbol<OrdValid> {
  GTC, GTD, GFD  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"OrdValid\",\"namespace\":\"io.cygnuxltb.jcts.core.ser.enums\",\"symbols\":[\"GTC\",\"GTD\",\"GFD\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
