/**
 * Autogenerated by Avro
 * <p>
 * DO NOT EDIT DIRECTLY
 */
package io.cygnuxltb.jcts.core.serialization.avro.enums;

@org.apache.avro.specific.AvroGenerated
public enum AEnumTrdAction implements org.apache.avro.generic.GenericEnumSymbol<AEnumTrdAction> {
    INVALID, OPEN, CLOSE, CLOSE_TODAY, CLOSE_YESTERDAY;
    public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"AEnumTrdAction\",\"namespace\":\"io.cygnuxltb.jcts.core.serialization.avro.enums\",\"symbols\":[\"INVALID\",\"OPEN\",\"CLOSE\",\"CLOSE_TODAY\",\"CLOSE_YESTERDAY\"]}");

    public static org.apache.avro.Schema getClassSchema() {
        return SCHEMA$;
    }

    public org.apache.avro.Schema getSchema() {
        return SCHEMA$;
    }
}
