/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.cygnuxltb.jcts.core.serialization.avro.enums;
/** 行情订阅状态 */
@org.apache.avro.specific.AvroGenerated
public enum AEnumSubscribeStatus implements org.apache.avro.generic.GenericEnumSymbol<AEnumSubscribeStatus> {
  SUCCEED, PART_SUCCEED, FAILED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"AEnumSubscribeStatus\",\"namespace\":\"io.cygnuxltb.jcts.core.serialization.avro.enums\",\"doc\":\"行情订阅状态\",\"symbols\":[\"SUCCEED\",\"PART_SUCCEED\",\"FAILED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
