/**
 * Autogenerated by Avro
 * <p>
 * DO NOT EDIT DIRECTLY
 */
package io.cygnuxltb.jcts.core.serialization.avro.enums;

@org.apache.avro.specific.AvroGenerated
public enum AEnumOrdValid implements org.apache.avro.generic.GenericEnumSymbol<AEnumOrdValid> {
    GTC, GTD, GFD;
    public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"AEnumOrdValid\",\"namespace\":\"io.cygnuxltb.jcts.core.serialization.avro.enums\",\"symbols\":[\"GTC\",\"GTD\",\"GFD\"]}");

    public static org.apache.avro.Schema getClassSchema() {
        return SCHEMA$;
    }

    public org.apache.avro.Schema getSchema() {
        return SCHEMA$;
    }
}
