/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.cygnuxltb.jcts.core.serialization.avro.enums;
@org.apache.avro.specific.AvroGenerated
public enum AEnumAdaptorStatus implements org.apache.avro.generic.GenericEnumSymbol<AEnumAdaptorStatus> {
  INVALID, UNAVAILABLE, MD_ENABLE, MD_DISABLE, TRADER_ENABLE, TRADER_DISABLE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"AEnumAdaptorStatus\",\"namespace\":\"io.cygnuxltb.jcts.core.serialization.avro.enums\",\"symbols\":[\"INVALID\",\"UNAVAILABLE\",\"MD_ENABLE\",\"MD_DISABLE\",\"TRADER_ENABLE\",\"TRADER_DISABLE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
