/**
 * Autogenerated by Avro
 * <p>
 * DO NOT EDIT DIRECTLY
 */
package io.rapid.core.event.inbound;

import io.mercury.common.serialization.Copyable;
import io.mercury.serialization.json.JsonBean;
import io.rapid.core.event.enums.TrdDirection;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.experimental.Accessors;

/**
 * 持仓回报
 */
@Getter
@Setter
@Accessors(chain = true)
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class PositionsReport extends JsonBean implements Copyable<PositionsReport> {

    private long epochMillis;
    private String brokerId;
    private String investorId;
    private String exchangeCode;
    private String instrumentCode;
    private TrdDirection direction;
    private int qty;

    @Override
    public void copyFrom(PositionsReport source) {
        // 1. 复制事件的时间戳
        this.epochMillis = source.getEpochMillis();
        // 2. 复制经纪商ID
        this.brokerId = source.getBrokerId();
        // 3. 复制投资者ID
        this.investorId = source.getInvestorId();
        // 4. 复制交易所代码
        this.exchangeCode = source.getExchangeCode();
        // 5. 复制交易标的代码
        this.instrumentCode = source.getInstrumentCode();
        // 6. 复制交易方向
        this.direction = source.getDirection();
        // 7. 复制持仓数量
        this.qty = source.getQty();
    }

}