<!DOCTYPE html>
<html lang="zh-Hans">
<head>
    <meta content="text/html; charset=UTF-8" charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="/style.css">
    <title>Rapid Backend Settings</title>
</head>
<body>
<p>
    -> 控制面板
</p>
<table id="customers">
    <thead id="console">
    <tr>
        <td>策略</td>
        <td>交易</td>
        <td>系统</td>
        <td>监控</td>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td><a href="/strategy/ui">策略管理</a></td>
        <td><a href="/adapter/ui">Adapter管理</a></td>
        <td><a href="#">系统指令</a></td>
        <td><a href="#">日志数据</a></td>
    </tr>
    <tr>
        <td><a href="/strategy/ui/param">策略参数</a></td>
        <td><a href="/adapter/ui/param">交易参数</a></td>
        <td><a href="#">用户管理</a></td>
        <td><a href="#">订单数据</a></td>
    </tr>
    <tr>
        <td></td>
        <td><a href="#">交易账户管理</a></td>
        <td><a href="#">动态修改参数</a></td>
        <td><a href="#">盈亏详情</a></td>
    </tr>
    <tr>
        <td></td>
        <td><a href="#">启动交易</a></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td colspan="7">
            <h5>列表数据显示说明</h5>
            <h6>用户名(用户ID)&nbsp;&nbsp;&nbsp;|
                &nbsp;&nbsp;&nbsp;策略名(策略ID/策略类型)&nbsp;&nbsp;&nbsp;|
                &nbsp;&nbsp;&nbsp;算法名(算法ID/算法类型)&nbsp;&nbsp;&nbsp;|
                &nbsp;&nbsp;&nbsp;Adaptor名(AdaptorID/Adaptor类型)</h6>
        </td>
    </tr>
    </tbody>
</table>
</body>
</html>
