/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.horizon.trader.serialization.avro.enums;
@org.apache.avro.specific.AvroGenerated
public enum AvroOrdSide implements org.apache.avro.generic.GenericEnumSymbol<AvroOrdSide> {
  INVALID, BUY, SELL, MARGIN_BUY, SHORT_SELL  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"AvroOrdSide\",\"namespace\":\"io.horizon.trader.serialization.avro.enums\",\"symbols\":[\"INVALID\",\"BUY\",\"SELL\",\"MARGIN_BUY\",\"SHORT_SELL\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
