/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.horizon.trader.serialization.avro.enums;
@org.apache.avro.specific.AvroGenerated
public enum AvroTrdAction implements org.apache.avro.generic.GenericEnumSymbol<AvroTrdAction> {
  INVALID, OPEN, CLOSE, CLOSE_TODAY, CLOSE_YESTERDAY  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"AvroTrdAction\",\"namespace\":\"io.horizon.trader.serialization.avro.enums\",\"symbols\":[\"INVALID\",\"OPEN\",\"CLOSE\",\"CLOSE_TODAY\",\"CLOSE_YESTERDAY\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
