/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.horizon.trader.serialization.avro.enums;
@org.apache.avro.specific.AvroGenerated
public enum AvroTrdDirection implements org.apache.avro.generic.GenericEnumSymbol<AvroTrdDirection> {
  INVALID, LONG, SHORT  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"AvroTrdDirection\",\"namespace\":\"io.horizon.trader.serialization.avro.enums\",\"symbols\":[\"INVALID\",\"LONG\",\"SHORT\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
