INSERT INTO "PUBLIC"."TBL_SYS_PARAM"
("OWNER_GROUP", "OWNER_NAME", "PARAM_GROUP", "PARAM_NAME", "PARAM_TYPE", "PARAM_VALUE")
VALUES ('SIMNOW', 'TRADE', '电信1', 'traderAddr', 'STRING', '180.168.146.187:10201')
     , ('SIMNOW', 'TRADE', '电信1', 'mdAddr', 'STRING', '180.168.146.187:10211')
     , ('SIMNOW', 'TRADE', '电信2', 'traderAddr', 'STRING', '180.168.146.187:10202')
     , ('SIMNOW', 'TRADE', '电信2', 'mdAddr', 'STRING', '180.168.146.187:10212')
     , ('SIMNOW', 'TRADE', '移动1', 'traderAddr', 'STRING', '218.202.237.33:10203')
     , ('SIMNOW', 'TRADE', '移动1', 'mdAddr', 'STRING', '218.202.237.33:10213')
     , ('SIMNOW', 'TEST', '测试1', 'traderAddr', 'STRING', '180.168.146.187:10130')
     , ('SIMNOW', 'TEST', '测试1', 'mdAddr', 'STRING', '180.168.146.187:10131')
     , ('SIMNOW', 'COMMON', '公用', 'appId', 'STRING', 'simnow_client_test')
     , ('SIMNOW', 'COMMON', '公用', 'authCode', 'STRING', '0000000000000000')
;

