INSERT INTO "PUBLIC"."SYS_PARAM"
("OWNER_GROUP", "OWNER_NAME", "PARAM_GROUP", "PARAM_NAME", "PARAM_TYPE", "PARAM_VALUE")
VALUES ('ADAPTOR', 'SIMNOW', 'ChinaTelecom1', 'traderAddr', 'STRING', '180.168.146.187:10201')
     , ('ADAPTOR', 'SIMNOW', 'ChinaTelecom1', 'mdAddr', 'STRING', '180.168.146.187:10211')
     , ('ADAPTOR', 'SIMNOW', 'ChinaTelecom2', 'traderAddr', 'STRING', '180.168.146.187:10202')
     , ('ADAPTOR', 'SIMNOW', 'ChinaTelecom2', 'mdAddr', 'STRING', '180.168.146.187:10212')
     , ('ADAPTOR', 'SIMNOW', 'ChinaMobile1', 'traderAddr', 'STRING', '218.202.237.33:10203')
     , ('ADAPTOR', 'SIMNOW', 'ChinaMobile1', 'mdAddr', 'STRING', '218.202.237.33:10213')
     , ('ADAPTOR', 'SIMNOW', '24x7_TEST1', 'traderAddr', 'STRING', '180.168.146.187:10130')
     , ('ADAPTOR', 'SIMNOW', '24x7_TEST1', 'mdAddr', 'STRING', '180.168.146.187:10131')
     , ('ADAPTOR', 'SIMNOW', '', 'appId', 'STRING', 'simnow_client_test')
     , ('ADAPTOR', 'SIMNOW', '', 'authCode', 'STRING', '0000000000000000')
;