/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.rapid.core.serializable.avro.outbound;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** 撤单 */
@org.apache.avro.specific.AvroGenerated
public class CancelOrder extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -2091697708910370742L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CancelOrder\",\"namespace\":\"io.rapid.core.serializable.avro.outbound\",\"doc\":\"撤单\",\"fields\":[{\"name\":\"generateTime\",\"type\":\"long\",\"doc\":\"Epoch Microsecond Unit\"},{\"name\":\"sendTime\",\"type\":\"long\",\"doc\":\"Epoch Microsecond Unit\"},{\"name\":\"ordSysId\",\"type\":\"long\",\"doc\":\"订单ID\"},{\"name\":\"instrumentCode\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"交易标的代码\"},{\"name\":\"exchangeCode\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"交易所代码\"},{\"name\":\"accountId\",\"type\":\"int\",\"doc\":\"账户ID\"},{\"name\":\"brokerId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"经纪商ID\"},{\"name\":\"subAccountId\",\"type\":\"int\",\"doc\":\"子账户ID\"},{\"name\":\"strategyId\",\"type\":\"int\",\"doc\":\"策略ID\"},{\"name\":\"delayMillis\",\"type\":\"long\",\"doc\":\"延迟时间\",\"default\":0},{\"name\":\"operatorId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"操作ID\",\"default\":\"\"},{\"name\":\"remark\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"备注\",\"default\":\"\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<CancelOrder> ENCODER =
      new BinaryMessageEncoder<CancelOrder>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<CancelOrder> DECODER =
      new BinaryMessageDecoder<CancelOrder>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<CancelOrder> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<CancelOrder> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<CancelOrder> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<CancelOrder>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this CancelOrder to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a CancelOrder from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a CancelOrder instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static CancelOrder fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Epoch Microsecond Unit */
  private long generateTime;
  /** Epoch Microsecond Unit */
  private long sendTime;
  /** 订单ID */
  private long ordSysId;
  /** 交易标的代码 */
  private java.lang.String instrumentCode;
  /** 交易所代码 */
  private java.lang.String exchangeCode;
  /** 账户ID */
  private int accountId;
  /** 经纪商ID */
  private java.lang.String brokerId;
  /** 子账户ID */
  private int subAccountId;
  /** 策略ID */
  private int strategyId;
  /** 延迟时间 */
  private long delayMillis;
  /** 操作ID */
  private java.lang.String operatorId;
  /** 备注 */
  private java.lang.String remark;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public CancelOrder() {}

  /**
   * All-args constructor.
   * @param generateTime Epoch Microsecond Unit
   * @param sendTime Epoch Microsecond Unit
   * @param ordSysId 订单ID
   * @param instrumentCode 交易标的代码
   * @param exchangeCode 交易所代码
   * @param accountId 账户ID
   * @param brokerId 经纪商ID
   * @param subAccountId 子账户ID
   * @param strategyId 策略ID
   * @param delayMillis 延迟时间
   * @param operatorId 操作ID
   * @param remark 备注
   */
  public CancelOrder(java.lang.Long generateTime, java.lang.Long sendTime, java.lang.Long ordSysId, java.lang.String instrumentCode, java.lang.String exchangeCode, java.lang.Integer accountId, java.lang.String brokerId, java.lang.Integer subAccountId, java.lang.Integer strategyId, java.lang.Long delayMillis, java.lang.String operatorId, java.lang.String remark) {
    this.generateTime = generateTime;
    this.sendTime = sendTime;
    this.ordSysId = ordSysId;
    this.instrumentCode = instrumentCode;
    this.exchangeCode = exchangeCode;
    this.accountId = accountId;
    this.brokerId = brokerId;
    this.subAccountId = subAccountId;
    this.strategyId = strategyId;
    this.delayMillis = delayMillis;
    this.operatorId = operatorId;
    this.remark = remark;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return generateTime;
    case 1: return sendTime;
    case 2: return ordSysId;
    case 3: return instrumentCode;
    case 4: return exchangeCode;
    case 5: return accountId;
    case 6: return brokerId;
    case 7: return subAccountId;
    case 8: return strategyId;
    case 9: return delayMillis;
    case 10: return operatorId;
    case 11: return remark;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: generateTime = (java.lang.Long)value$; break;
    case 1: sendTime = (java.lang.Long)value$; break;
    case 2: ordSysId = (java.lang.Long)value$; break;
    case 3: instrumentCode = value$ != null ? value$.toString() : null; break;
    case 4: exchangeCode = value$ != null ? value$.toString() : null; break;
    case 5: accountId = (java.lang.Integer)value$; break;
    case 6: brokerId = value$ != null ? value$.toString() : null; break;
    case 7: subAccountId = (java.lang.Integer)value$; break;
    case 8: strategyId = (java.lang.Integer)value$; break;
    case 9: delayMillis = (java.lang.Long)value$; break;
    case 10: operatorId = value$ != null ? value$.toString() : null; break;
    case 11: remark = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'generateTime' field.
   * @return Epoch Microsecond Unit
   */
  public long getGenerateTime() {
    return generateTime;
  }


  /**
   * Sets the value of the 'generateTime' field.
   * Epoch Microsecond Unit
   * @param value the value to set.
   */
  public CancelOrder setGenerateTime(long value) {
    this.generateTime = value;
    return this;
  }

  /**
   * Gets the value of the 'sendTime' field.
   * @return Epoch Microsecond Unit
   */
  public long getSendTime() {
    return sendTime;
  }


  /**
   * Sets the value of the 'sendTime' field.
   * Epoch Microsecond Unit
   * @param value the value to set.
   */
  public CancelOrder setSendTime(long value) {
    this.sendTime = value;
    return this;
  }

  /**
   * Gets the value of the 'ordSysId' field.
   * @return 订单ID
   */
  public long getOrdSysId() {
    return ordSysId;
  }


  /**
   * Sets the value of the 'ordSysId' field.
   * 订单ID
   * @param value the value to set.
   */
  public CancelOrder setOrdSysId(long value) {
    this.ordSysId = value;
    return this;
  }

  /**
   * Gets the value of the 'instrumentCode' field.
   * @return 交易标的代码
   */
  public java.lang.String getInstrumentCode() {
    return instrumentCode;
  }


  /**
   * Sets the value of the 'instrumentCode' field.
   * 交易标的代码
   * @param value the value to set.
   */
  public CancelOrder setInstrumentCode(java.lang.String value) {
    this.instrumentCode = value;
    return this;
  }

  /**
   * Gets the value of the 'exchangeCode' field.
   * @return 交易所代码
   */
  public java.lang.String getExchangeCode() {
    return exchangeCode;
  }


  /**
   * Sets the value of the 'exchangeCode' field.
   * 交易所代码
   * @param value the value to set.
   */
  public CancelOrder setExchangeCode(java.lang.String value) {
    this.exchangeCode = value;
    return this;
  }

  /**
   * Gets the value of the 'accountId' field.
   * @return 账户ID
   */
  public int getAccountId() {
    return accountId;
  }


  /**
   * Sets the value of the 'accountId' field.
   * 账户ID
   * @param value the value to set.
   */
  public CancelOrder setAccountId(int value) {
    this.accountId = value;
    return this;
  }

  /**
   * Gets the value of the 'brokerId' field.
   * @return 经纪商ID
   */
  public java.lang.String getBrokerId() {
    return brokerId;
  }


  /**
   * Sets the value of the 'brokerId' field.
   * 经纪商ID
   * @param value the value to set.
   */
  public CancelOrder setBrokerId(java.lang.String value) {
    this.brokerId = value;
    return this;
  }

  /**
   * Gets the value of the 'subAccountId' field.
   * @return 子账户ID
   */
  public int getSubAccountId() {
    return subAccountId;
  }


  /**
   * Sets the value of the 'subAccountId' field.
   * 子账户ID
   * @param value the value to set.
   */
  public CancelOrder setSubAccountId(int value) {
    this.subAccountId = value;
    return this;
  }

  /**
   * Gets the value of the 'strategyId' field.
   * @return 策略ID
   */
  public int getStrategyId() {
    return strategyId;
  }


  /**
   * Sets the value of the 'strategyId' field.
   * 策略ID
   * @param value the value to set.
   */
  public CancelOrder setStrategyId(int value) {
    this.strategyId = value;
    return this;
  }

  /**
   * Gets the value of the 'delayMillis' field.
   * @return 延迟时间
   */
  public long getDelayMillis() {
    return delayMillis;
  }


  /**
   * Sets the value of the 'delayMillis' field.
   * 延迟时间
   * @param value the value to set.
   */
  public CancelOrder setDelayMillis(long value) {
    this.delayMillis = value;
    return this;
  }

  /**
   * Gets the value of the 'operatorId' field.
   * @return 操作ID
   */
  public java.lang.String getOperatorId() {
    return operatorId;
  }


  /**
   * Sets the value of the 'operatorId' field.
   * 操作ID
   * @param value the value to set.
   */
  public CancelOrder setOperatorId(java.lang.String value) {
    this.operatorId = value;
    return this;
  }

  /**
   * Gets the value of the 'remark' field.
   * @return 备注
   */
  public java.lang.String getRemark() {
    return remark;
  }


  /**
   * Sets the value of the 'remark' field.
   * 备注
   * @param value the value to set.
   */
  public CancelOrder setRemark(java.lang.String value) {
    this.remark = value;
    return this;
  }

  /**
   * Creates a new CancelOrder RecordBuilder.
   * @return A new CancelOrder RecordBuilder
   */
  public static io.rapid.core.serializable.avro.outbound.CancelOrder.Builder newBuilder() {
    return new io.rapid.core.serializable.avro.outbound.CancelOrder.Builder();
  }

  /**
   * Creates a new CancelOrder RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new CancelOrder RecordBuilder
   */
  public static io.rapid.core.serializable.avro.outbound.CancelOrder.Builder newBuilder(io.rapid.core.serializable.avro.outbound.CancelOrder.Builder other) {
    if (other == null) {
      return new io.rapid.core.serializable.avro.outbound.CancelOrder.Builder();
    } else {
      return new io.rapid.core.serializable.avro.outbound.CancelOrder.Builder(other);
    }
  }

  /**
   * Creates a new CancelOrder RecordBuilder by copying an existing CancelOrder instance.
   * @param other The existing instance to copy.
   * @return A new CancelOrder RecordBuilder
   */
  public static io.rapid.core.serializable.avro.outbound.CancelOrder.Builder newBuilder(io.rapid.core.serializable.avro.outbound.CancelOrder other) {
    if (other == null) {
      return new io.rapid.core.serializable.avro.outbound.CancelOrder.Builder();
    } else {
      return new io.rapid.core.serializable.avro.outbound.CancelOrder.Builder(other);
    }
  }

  /**
   * RecordBuilder for CancelOrder instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CancelOrder>
    implements org.apache.avro.data.RecordBuilder<CancelOrder> {

    /** Epoch Microsecond Unit */
    private long generateTime;
    /** Epoch Microsecond Unit */
    private long sendTime;
    /** 订单ID */
    private long ordSysId;
    /** 交易标的代码 */
    private java.lang.String instrumentCode;
    /** 交易所代码 */
    private java.lang.String exchangeCode;
    /** 账户ID */
    private int accountId;
    /** 经纪商ID */
    private java.lang.String brokerId;
    /** 子账户ID */
    private int subAccountId;
    /** 策略ID */
    private int strategyId;
    /** 延迟时间 */
    private long delayMillis;
    /** 操作ID */
    private java.lang.String operatorId;
    /** 备注 */
    private java.lang.String remark;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(io.rapid.core.serializable.avro.outbound.CancelOrder.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.generateTime)) {
        this.generateTime = data().deepCopy(fields()[0].schema(), other.generateTime);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.sendTime)) {
        this.sendTime = data().deepCopy(fields()[1].schema(), other.sendTime);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.ordSysId)) {
        this.ordSysId = data().deepCopy(fields()[2].schema(), other.ordSysId);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.instrumentCode)) {
        this.instrumentCode = data().deepCopy(fields()[3].schema(), other.instrumentCode);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.exchangeCode)) {
        this.exchangeCode = data().deepCopy(fields()[4].schema(), other.exchangeCode);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.accountId)) {
        this.accountId = data().deepCopy(fields()[5].schema(), other.accountId);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.brokerId)) {
        this.brokerId = data().deepCopy(fields()[6].schema(), other.brokerId);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.subAccountId)) {
        this.subAccountId = data().deepCopy(fields()[7].schema(), other.subAccountId);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.strategyId)) {
        this.strategyId = data().deepCopy(fields()[8].schema(), other.strategyId);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.delayMillis)) {
        this.delayMillis = data().deepCopy(fields()[9].schema(), other.delayMillis);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
      if (isValidValue(fields()[10], other.operatorId)) {
        this.operatorId = data().deepCopy(fields()[10].schema(), other.operatorId);
        fieldSetFlags()[10] = other.fieldSetFlags()[10];
      }
      if (isValidValue(fields()[11], other.remark)) {
        this.remark = data().deepCopy(fields()[11].schema(), other.remark);
        fieldSetFlags()[11] = other.fieldSetFlags()[11];
      }
    }

    /**
     * Creates a Builder by copying an existing CancelOrder instance
     * @param other The existing instance to copy.
     */
    private Builder(io.rapid.core.serializable.avro.outbound.CancelOrder other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.generateTime)) {
        this.generateTime = data().deepCopy(fields()[0].schema(), other.generateTime);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.sendTime)) {
        this.sendTime = data().deepCopy(fields()[1].schema(), other.sendTime);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.ordSysId)) {
        this.ordSysId = data().deepCopy(fields()[2].schema(), other.ordSysId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.instrumentCode)) {
        this.instrumentCode = data().deepCopy(fields()[3].schema(), other.instrumentCode);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.exchangeCode)) {
        this.exchangeCode = data().deepCopy(fields()[4].schema(), other.exchangeCode);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.accountId)) {
        this.accountId = data().deepCopy(fields()[5].schema(), other.accountId);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.brokerId)) {
        this.brokerId = data().deepCopy(fields()[6].schema(), other.brokerId);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.subAccountId)) {
        this.subAccountId = data().deepCopy(fields()[7].schema(), other.subAccountId);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.strategyId)) {
        this.strategyId = data().deepCopy(fields()[8].schema(), other.strategyId);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.delayMillis)) {
        this.delayMillis = data().deepCopy(fields()[9].schema(), other.delayMillis);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.operatorId)) {
        this.operatorId = data().deepCopy(fields()[10].schema(), other.operatorId);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.remark)) {
        this.remark = data().deepCopy(fields()[11].schema(), other.remark);
        fieldSetFlags()[11] = true;
      }
    }

    /**
      * Gets the value of the 'generateTime' field.
      * Epoch Microsecond Unit
      * @return The value.
      */
    public long getGenerateTime() {
      return generateTime;
    }


    /**
      * Sets the value of the 'generateTime' field.
      * Epoch Microsecond Unit
      * @param value The value of 'generateTime'.
      * @return This builder.
      */
    public io.rapid.core.serializable.avro.outbound.CancelOrder.Builder setGenerateTime(long value) {
      validate(fields()[0], value);
      this.generateTime = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'generateTime' field has been set.
      * Epoch Microsecond Unit
      * @return True if the 'generateTime' field has been set, false otherwise.
      */
    public boolean hasGenerateTime() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'generateTime' field.
      * Epoch Microsecond Unit
      * @return This builder.
      */
    public io.rapid.core.serializable.avro.outbound.CancelOrder.Builder clearGenerateTime() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'sendTime' field.
      * Epoch Microsecond Unit
      * @return The value.
      */
    public long getSendTime() {
      return sendTime;
    }


    /**
      * Sets the value of the 'sendTime' field.
      * Epoch Microsecond Unit
      * @param value The value of 'sendTime'.
      * @return This builder.
      */
    public io.rapid.core.serializable.avro.outbound.CancelOrder.Builder setSendTime(long value) {
      validate(fields()[1], value);
      this.sendTime = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'sendTime' field has been set.
      * Epoch Microsecond Unit
      * @return True if the 'sendTime' field has been set, false otherwise.
      */
    public boolean hasSendTime() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'sendTime' field.
      * Epoch Microsecond Unit
      * @return This builder.
      */
    public io.rapid.core.serializable.avro.outbound.CancelOrder.Builder clearSendTime() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'ordSysId' field.
      * 订单ID
      * @return The value.
      */
    public long getOrdSysId() {
      return ordSysId;
    }


    /**
      * Sets the value of the 'ordSysId' field.
      * 订单ID
      * @param value The value of 'ordSysId'.
      * @return This builder.
      */
    public io.rapid.core.serializable.avro.outbound.CancelOrder.Builder setOrdSysId(long value) {
      validate(fields()[2], value);
      this.ordSysId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'ordSysId' field has been set.
      * 订单ID
      * @return True if the 'ordSysId' field has been set, false otherwise.
      */
    public boolean hasOrdSysId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'ordSysId' field.
      * 订单ID
      * @return This builder.
      */
    public io.rapid.core.serializable.avro.outbound.CancelOrder.Builder clearOrdSysId() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'instrumentCode' field.
      * 交易标的代码
      * @return The value.
      */
    public java.lang.String getInstrumentCode() {
      return instrumentCode;
    }


    /**
      * Sets the value of the 'instrumentCode' field.
      * 交易标的代码
      * @param value The value of 'instrumentCode'.
      * @return This builder.
      */
    public io.rapid.core.serializable.avro.outbound.CancelOrder.Builder setInstrumentCode(java.lang.String value) {
      validate(fields()[3], value);
      this.instrumentCode = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'instrumentCode' field has been set.
      * 交易标的代码
      * @return True if the 'instrumentCode' field has been set, false otherwise.
      */
    public boolean hasInstrumentCode() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'instrumentCode' field.
      * 交易标的代码
      * @return This builder.
      */
    public io.rapid.core.serializable.avro.outbound.CancelOrder.Builder clearInstrumentCode() {
      instrumentCode = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'exchangeCode' field.
      * 交易所代码
      * @return The value.
      */
    public java.lang.String getExchangeCode() {
      return exchangeCode;
    }


    /**
      * Sets the value of the 'exchangeCode' field.
      * 交易所代码
      * @param value The value of 'exchangeCode'.
      * @return This builder.
      */
    public io.rapid.core.serializable.avro.outbound.CancelOrder.Builder setExchangeCode(java.lang.String value) {
      validate(fields()[4], value);
      this.exchangeCode = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'exchangeCode' field has been set.
      * 交易所代码
      * @return True if the 'exchangeCode' field has been set, false otherwise.
      */
    public boolean hasExchangeCode() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'exchangeCode' field.
      * 交易所代码
      * @return This builder.
      */
    public io.rapid.core.serializable.avro.outbound.CancelOrder.Builder clearExchangeCode() {
      exchangeCode = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'accountId' field.
      * 账户ID
      * @return The value.
      */
    public int getAccountId() {
      return accountId;
    }


    /**
      * Sets the value of the 'accountId' field.
      * 账户ID
      * @param value The value of 'accountId'.
      * @return This builder.
      */
    public io.rapid.core.serializable.avro.outbound.CancelOrder.Builder setAccountId(int value) {
      validate(fields()[5], value);
      this.accountId = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'accountId' field has been set.
      * 账户ID
      * @return True if the 'accountId' field has been set, false otherwise.
      */
    public boolean hasAccountId() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'accountId' field.
      * 账户ID
      * @return This builder.
      */
    public io.rapid.core.serializable.avro.outbound.CancelOrder.Builder clearAccountId() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'brokerId' field.
      * 经纪商ID
      * @return The value.
      */
    public java.lang.String getBrokerId() {
      return brokerId;
    }


    /**
      * Sets the value of the 'brokerId' field.
      * 经纪商ID
      * @param value The value of 'brokerId'.
      * @return This builder.
      */
    public io.rapid.core.serializable.avro.outbound.CancelOrder.Builder setBrokerId(java.lang.String value) {
      validate(fields()[6], value);
      this.brokerId = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'brokerId' field has been set.
      * 经纪商ID
      * @return True if the 'brokerId' field has been set, false otherwise.
      */
    public boolean hasBrokerId() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'brokerId' field.
      * 经纪商ID
      * @return This builder.
      */
    public io.rapid.core.serializable.avro.outbound.CancelOrder.Builder clearBrokerId() {
      brokerId = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'subAccountId' field.
      * 子账户ID
      * @return The value.
      */
    public int getSubAccountId() {
      return subAccountId;
    }


    /**
      * Sets the value of the 'subAccountId' field.
      * 子账户ID
      * @param value The value of 'subAccountId'.
      * @return This builder.
      */
    public io.rapid.core.serializable.avro.outbound.CancelOrder.Builder setSubAccountId(int value) {
      validate(fields()[7], value);
      this.subAccountId = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'subAccountId' field has been set.
      * 子账户ID
      * @return True if the 'subAccountId' field has been set, false otherwise.
      */
    public boolean hasSubAccountId() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'subAccountId' field.
      * 子账户ID
      * @return This builder.
      */
    public io.rapid.core.serializable.avro.outbound.CancelOrder.Builder clearSubAccountId() {
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'strategyId' field.
      * 策略ID
      * @return The value.
      */
    public int getStrategyId() {
      return strategyId;
    }


    /**
      * Sets the value of the 'strategyId' field.
      * 策略ID
      * @param value The value of 'strategyId'.
      * @return This builder.
      */
    public io.rapid.core.serializable.avro.outbound.CancelOrder.Builder setStrategyId(int value) {
      validate(fields()[8], value);
      this.strategyId = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'strategyId' field has been set.
      * 策略ID
      * @return True if the 'strategyId' field has been set, false otherwise.
      */
    public boolean hasStrategyId() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'strategyId' field.
      * 策略ID
      * @return This builder.
      */
    public io.rapid.core.serializable.avro.outbound.CancelOrder.Builder clearStrategyId() {
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'delayMillis' field.
      * 延迟时间
      * @return The value.
      */
    public long getDelayMillis() {
      return delayMillis;
    }


    /**
      * Sets the value of the 'delayMillis' field.
      * 延迟时间
      * @param value The value of 'delayMillis'.
      * @return This builder.
      */
    public io.rapid.core.serializable.avro.outbound.CancelOrder.Builder setDelayMillis(long value) {
      validate(fields()[9], value);
      this.delayMillis = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'delayMillis' field has been set.
      * 延迟时间
      * @return True if the 'delayMillis' field has been set, false otherwise.
      */
    public boolean hasDelayMillis() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'delayMillis' field.
      * 延迟时间
      * @return This builder.
      */
    public io.rapid.core.serializable.avro.outbound.CancelOrder.Builder clearDelayMillis() {
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'operatorId' field.
      * 操作ID
      * @return The value.
      */
    public java.lang.String getOperatorId() {
      return operatorId;
    }


    /**
      * Sets the value of the 'operatorId' field.
      * 操作ID
      * @param value The value of 'operatorId'.
      * @return This builder.
      */
    public io.rapid.core.serializable.avro.outbound.CancelOrder.Builder setOperatorId(java.lang.String value) {
      validate(fields()[10], value);
      this.operatorId = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'operatorId' field has been set.
      * 操作ID
      * @return True if the 'operatorId' field has been set, false otherwise.
      */
    public boolean hasOperatorId() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'operatorId' field.
      * 操作ID
      * @return This builder.
      */
    public io.rapid.core.serializable.avro.outbound.CancelOrder.Builder clearOperatorId() {
      operatorId = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'remark' field.
      * 备注
      * @return The value.
      */
    public java.lang.String getRemark() {
      return remark;
    }


    /**
      * Sets the value of the 'remark' field.
      * 备注
      * @param value The value of 'remark'.
      * @return This builder.
      */
    public io.rapid.core.serializable.avro.outbound.CancelOrder.Builder setRemark(java.lang.String value) {
      validate(fields()[11], value);
      this.remark = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'remark' field has been set.
      * 备注
      * @return True if the 'remark' field has been set, false otherwise.
      */
    public boolean hasRemark() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'remark' field.
      * 备注
      * @return This builder.
      */
    public io.rapid.core.serializable.avro.outbound.CancelOrder.Builder clearRemark() {
      remark = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    @Override
    public CancelOrder build() {
      try {
        CancelOrder record = new CancelOrder();
        record.generateTime = fieldSetFlags()[0] ? this.generateTime : (java.lang.Long) defaultValue(fields()[0]);
        record.sendTime = fieldSetFlags()[1] ? this.sendTime : (java.lang.Long) defaultValue(fields()[1]);
        record.ordSysId = fieldSetFlags()[2] ? this.ordSysId : (java.lang.Long) defaultValue(fields()[2]);
        record.instrumentCode = fieldSetFlags()[3] ? this.instrumentCode : (java.lang.String) defaultValue(fields()[3]);
        record.exchangeCode = fieldSetFlags()[4] ? this.exchangeCode : (java.lang.String) defaultValue(fields()[4]);
        record.accountId = fieldSetFlags()[5] ? this.accountId : (java.lang.Integer) defaultValue(fields()[5]);
        record.brokerId = fieldSetFlags()[6] ? this.brokerId : (java.lang.String) defaultValue(fields()[6]);
        record.subAccountId = fieldSetFlags()[7] ? this.subAccountId : (java.lang.Integer) defaultValue(fields()[7]);
        record.strategyId = fieldSetFlags()[8] ? this.strategyId : (java.lang.Integer) defaultValue(fields()[8]);
        record.delayMillis = fieldSetFlags()[9] ? this.delayMillis : (java.lang.Long) defaultValue(fields()[9]);
        record.operatorId = fieldSetFlags()[10] ? this.operatorId : (java.lang.String) defaultValue(fields()[10]);
        record.remark = fieldSetFlags()[11] ? this.remark : (java.lang.String) defaultValue(fields()[11]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<CancelOrder>
    WRITER$ = (org.apache.avro.io.DatumWriter<CancelOrder>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<CancelOrder>
    READER$ = (org.apache.avro.io.DatumReader<CancelOrder>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this.generateTime);

    out.writeLong(this.sendTime);

    out.writeLong(this.ordSysId);

    out.writeString(this.instrumentCode);

    out.writeString(this.exchangeCode);

    out.writeInt(this.accountId);

    out.writeString(this.brokerId);

    out.writeInt(this.subAccountId);

    out.writeInt(this.strategyId);

    out.writeLong(this.delayMillis);

    out.writeString(this.operatorId);

    out.writeString(this.remark);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.generateTime = in.readLong();

      this.sendTime = in.readLong();

      this.ordSysId = in.readLong();

      this.instrumentCode = in.readString();

      this.exchangeCode = in.readString();

      this.accountId = in.readInt();

      this.brokerId = in.readString();

      this.subAccountId = in.readInt();

      this.strategyId = in.readInt();

      this.delayMillis = in.readLong();

      this.operatorId = in.readString();

      this.remark = in.readString();

    } else {
      for (int i = 0; i < 12; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.generateTime = in.readLong();
          break;

        case 1:
          this.sendTime = in.readLong();
          break;

        case 2:
          this.ordSysId = in.readLong();
          break;

        case 3:
          this.instrumentCode = in.readString();
          break;

        case 4:
          this.exchangeCode = in.readString();
          break;

        case 5:
          this.accountId = in.readInt();
          break;

        case 6:
          this.brokerId = in.readString();
          break;

        case 7:
          this.subAccountId = in.readInt();
          break;

        case 8:
          this.strategyId = in.readInt();
          break;

        case 9:
          this.delayMillis = in.readLong();
          break;

        case 10:
          this.operatorId = in.readString();
          break;

        case 11:
          this.remark = in.readString();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










