/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.rapid.core.protocol.avro.enums;
@org.apache.avro.specific.AvroGenerated
public enum OrdLevel implements org.apache.avro.generic.GenericEnumSymbol<OrdLevel> {
  CHILD, PARENT, STRATEGY, GROUP  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"OrdLevel\",\"namespace\":\"io.rapid.core.protocol.avro.enums\",\"symbols\":[\"CHILD\",\"PARENT\",\"STRATEGY\",\"GROUP\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
